@extends('index')
@section('content')
	<br>
	<div class="fondo">
        <br>
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <td>Municipio</td>
                <td>Localidad</td>
                <td>Colonia</td>
                <td>Código Postal</td>
                <td>Número de Carpeta</td>
                <td>Delito</td>
                <td>UIPJ</td>
                <td>Acción</td>
                <td>Virus</td>
            </thead>
            <tbody>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
            </tbody>
        </table>

    </div>

@stop