@extends('index')
@section('content')
	<br>
    <div class="fondo">
    <br>    
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <td>Número de Carpeta</td>
                <td>UIPJ</td>
                <td>Regino</td>
                <td>Nombre</td>
                <td>Primer Apellido</td>
                <td>Segundo Apellido</td>
                <td>Acción</td>
            </thead>
            <tbody>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
                <tr>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>XXXXXXXXXX</td>
                   <td>Detalle</td> 
                </tr>
            </tbody>
        </table>

    </div>
@stop