@extends('index')
@section('content')

<div  id="denunciante">
    <br>
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <td>Nombre</td>
            <td>Primer Apellido</td>
            <td>Segundo Apellido</td>
            <td>Número de Carpeta</td>
            <td>Delito</td>
            <td>Regional</td>
            <td>UIPJ</td>
            <td>Acción</td>
        </thead>
        <tbody>
            <tr>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>Detalle</td> 
            </tr>
            <tr>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>Detalle</td> 
            </tr>
            <tr>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>Detalle</td> 
            </tr>
            <tr>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>Detalle</td> 
            </tr>
            <tr>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>Detalle</td> 
            </tr>
            <tr>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>Detalle</td> 
            </tr>
            <tr>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>Detalle</td> 
            </tr>
            <tr>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>XXXXXXXXXX</td>
               <td>Detalle</td> 
            </tr>
        </tbody>
    </table>

</div>

@stop